name = "contact-worker"
main = "contact.js"
compatibility_date = "2025-09-28"
workers_dev = false

routes = [
  { pattern = "vineshore.org/api/contact", zone_name = "vineshore.org" },
  { pattern = "www.vineshore.org/api/contact", zone_name = "vineshore.org" },
  { pattern = "home.vineshore.org/api/contact", zone_name = "vineshore.org" }
]

kv_namespaces = [
  { binding = "CONTACT_RATE", id = "bd8862d33afb456a95cc93bf5b172a80" }
]

[vars]
CONTACT_TO = "admin@vineshore.org"
CONTACT_FROM = "webform@vineshore.org"
RATE_LIMIT_PER_HOUR = "5"

# 不再使用 [[email]] 绑定（SendGrid/Resend 通过 HTTP API）
